import type { SkillMethods, SkillProvenance } from "@/lib/skills-api";

/**
 * A representative publish-confidence bundle for the MSW mock (B4), so the panel
 * renders in offline dev (`npm run dev:mock`). The real bundle is produced by the
 * backend (provenance.py / methods.py); this just mirrors the shape with plausible
 * content keyed off the skill + its params.
 */
const MOCK_PKGS = {
  scanpy: "1.10.3",
  anndata: "0.11.1",
  "scikit-learn": "1.5.2",
  plotly: "6.1.1",
  numpy: "2.1.3",
  pandas: "2.2.3",
};

const METHODS: Record<string, string> = {
  umap_scrna:
    "Single-cell RNA-seq data were processed with Scanpy. Counts were normalized and log1p-transformed, then embedded in two dimensions with UMAP over the top principal components.",
  cluster:
    "Cells were clustered by Leiden community detection, and cluster-separation quality was quantified by the mean silhouette coefficient on the PCA embedding.",
  deg:
    "Differential expression was assessed by the Wilcoxon rank-sum test (single-cell) or PyDESeq2 (bulk), with Benjamini-Hochberg correction for multiple testing.",
  volcano:
    "Differential-expression results were displayed as a volcano plot of -log10 adjusted p-value against log2 fold change, with significant genes labelled.",
  heatmap:
    "Expression of the top genes was z-scored per gene and displayed as a heatmap with hierarchical row ordering (correlation distance, average linkage).",
  enrichment:
    "Pathway enrichment was computed by hypergeometric over-representation analysis against GO and Reactome gene sets, with Benjamini-Hochberg correction.",
};

export function mockBundle(
  skillId: string,
  params: Record<string, string>,
): { provenance: SkillProvenance; methods: SkillMethods } {
  const base = METHODS[skillId] ?? `Figure generated by the Selom '${skillId}' skill.`;
  return {
    provenance: {
      skill: { id: skillId, version: "0.1.0", title: titleize(skillId), engine: "python" },
      params,
      input: {
        filename: "demo.h5ad",
        sha256: "0a0b722d98d5e91b4ba94d52f0e3c7a18b6c4d2e9f10a3b5c6d7e8f90a1b2c3d4",
        n_bytes: 21_233_664,
      },
      environment: {
        python: "3.12.13",
        platform: "mock-offline",
        engine_policy: "stub",
        packages: MOCK_PKGS,
      },
    },
    methods: {
      text: `${base} Analysis was performed using Selom (skill '${skillId}' v0.1.0).`,
      citations: [
        "Wolf, F.A., Angerer, P. & Theis, F.J. SCANPY: large-scale single-cell gene expression data analysis. Genome Biology 19, 15 (2018).",
      ],
    },
  };
}

function titleize(slug: string): string {
  return slug.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}
