import type { SkillGuardrail, SkillMethods, SkillProvenance } from "@/lib/skills-api";

/**
 * A representative publish-confidence bundle for the MSW mock (B4), so the panel
 * renders in offline dev (`npm run dev:mock`). The real bundle is produced by the
 * backend (provenance.py / methods.py); this just mirrors the shape with plausible
 * content keyed off the skill + its params.
 */
const MOCK_PKGS = {
  scanpy: "1.10.3",
  anndata: "0.11.1",
  "scikit-learn": "1.5.2",
  plotly: "6.1.1",
  numpy: "2.1.3",
  pandas: "2.2.3",
};

const METHODS: Record<string, string> = {
  umap_scrna:
    "Single-cell RNA-seq data were processed with Scanpy. Counts were normalized and log1p-transformed, then embedded in two dimensions with UMAP over the top principal components.",
  cluster:
    "Cells were clustered by Leiden community detection, and cluster-separation quality was quantified by the mean silhouette coefficient on the PCA embedding.",
  deg:
    "Differential expression was assessed by the Wilcoxon rank-sum test (single-cell) or PyDESeq2 (bulk), with Benjamini-Hochberg correction for multiple testing.",
  volcano:
    "Differential-expression results were displayed as a volcano plot of -log10 adjusted p-value against log2 fold change, with significant genes labelled.",
  heatmap:
    "Expression of the top genes was z-scored per gene and displayed as a heatmap with hierarchical row ordering (correlation distance, average linkage).",
  enrichment:
    "Pathway enrichment was computed by hypergeometric over-representation analysis against GO and Reactome gene sets, with Benjamini-Hochberg correction.",
  markers:
    "Marker genes were ranked per cluster with the Wilcoxon rank-sum test (Scanpy rank_genes_groups) and shown as a dotplot — colour = mean log1p expression, dot size = fraction of cells expressing.",
  annotate:
    "Cell types were assigned by scoring curated marker sets per cell (Scanpy score_genes), averaging per cluster, and labelling each cluster with its top-scoring type; the embedding is recoloured by assigned type.",
  trajectory:
    "A diffusion map was computed, the cluster graph abstracted with PAGA, and cells ordered along diffusion pseudotime (DPT); the embedding is coloured by pseudotime with the PAGA graph overlaid.",
  pca:
    "Samples were projected onto their first two principal components (scikit-learn PCA) and coloured by group; variance explained is shown per axis.",
  composition:
    "Category proportions (e.g. cell-type deconvolution) were displayed as grouped bars across conditions.",
  proteomics_de:
    "Protein intensities were log2-transformed and median-normalized across samples; sparse proteins were filtered and residual missing values mean-imputed per group. Differential abundance between groups was tested with a Welch t-test and Benjamini-Hochberg correction, displayed as a volcano plot.",
  gsea:
    "Genes were ranked by the signed differential statistic and tested for gene-set enrichment with a weighted Kolmogorov-Smirnov running enrichment score (Subramanian et al. 2005); a normalized enrichment score and empirical p-value were estimated by permutation.",
  corr_heatmap:
    "Pairwise Pearson correlation coefficients were computed between samples and displayed as a heatmap on a diverging colour scale centred at zero, with rows and columns reordered by hierarchical clustering (1−r distance, average linkage).",
  upset:
    "Set membership was summarized as an UpSet plot: intersection sizes are shown as bars above a dot-matrix of set membership, with the largest intersections displayed.",
};

// Mirrors backend guardrails.py for the canned demo input (a clean raw-count h5ad):
// FDR skills always report multiple-testing; a lax fdr_threshold query adds a warning.
const FDR_SKILLS = new Set(["deg", "volcano", "enrichment", "proteomics_de"]);

function mockGuardrails(skillId: string, params: Record<string, string>): SkillGuardrail[] {
  const out: SkillGuardrail[] = [];
  if (FDR_SKILLS.has(skillId)) {
    out.push({
      level: "info",
      code: "multiple-testing",
      title: "Multiple-testing correction applied",
      detail: "p-values are corrected across genes/sets by the Benjamini–Hochberg FDR procedure.",
    });
  }
  const fdr = Number(params.fdr_threshold);
  if (Number.isFinite(fdr) && fdr > 0.1) {
    out.push({
      level: "warn",
      code: "fdr-threshold",
      title: fdr >= 1 ? "No FDR filtering" : "Lax FDR threshold",
      detail: `fdr_threshold = ${fdr}: thresholds above 0.1 inflate false positives; 0.05 is conventional.`,
    });
  }
  return out;
}

export function mockBundle(
  skillId: string,
  params: Record<string, string>,
): { provenance: SkillProvenance; methods: SkillMethods; guardrails: SkillGuardrail[] } {
  const base = METHODS[skillId] ?? `Figure generated by the Selom '${skillId}' skill.`;
  return {
    guardrails: mockGuardrails(skillId, params),
    provenance: {
      skill: { id: skillId, version: "0.1.0", title: titleize(skillId), engine: "python" },
      params,
      input: {
        filename: "demo.h5ad",
        sha256: "0a0b722d98d5e91b4ba94d52f0e3c7a18b6c4d2e9f10a3b5c6d7e8f90a1b2c3d4",
        n_bytes: 21_233_664,
      },
      environment: {
        python: "3.12.13",
        platform: "mock-offline",
        engine_policy: "stub",
        packages: MOCK_PKGS,
      },
    },
    methods: {
      text: `${base} Analysis was performed using Selom (skill '${skillId}' v0.1.0).`,
      citations: [
        "Wolf, F.A., Angerer, P. & Theis, F.J. SCANPY: large-scale single-cell gene expression data analysis. Genome Biology 19, 15 (2018).",
      ],
    },
  };
}

function titleize(slug: string): string {
  return slug.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}
