"use client";

import * as React from "react";
import { Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { questionsFor, type IntakeAnswers } from "@/lib/intake/mock";
import type { Modality } from "@/lib/projects/types";

/**
 * The guided-intake questionnaire (design §4.2). Shown after upload when no skills
 * are pre-picked; skippable. Adapts its fields to the detected modality. On submit
 * it hands the answers up — the LLM proposal (mock) is generated by the workbench.
 */
export function IntakeQuestionnaire({
  modality,
  onSubmit,
  onSkip,
}: {
  modality: Modality;
  onSubmit: (answers: IntakeAnswers) => void;
  onSkip: () => void;
}) {
  const questions = questionsFor(modality);
  const [answers, setAnswers] = React.useState<IntakeAnswers>({});

  function set(id: string, v: string) {
    setAnswers((a) => ({ ...a, [id]: v }));
  }

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        onSubmit(answers);
      }}
      className="space-y-4"
    >
      <div className="flex items-center gap-2">
        <Sparkles className="size-4 text-primary" />
        <p className="text-sm font-medium text-foreground">
          Tell Selom about your data
        </p>
        <span className="tabular rounded border border-border px-1.5 py-0.5 text-[10px] uppercase tracking-wider text-muted-foreground">
          {modality}
        </span>
      </div>
      <p className="-mt-1 text-xs text-muted-foreground">
        A few questions so the assistant can propose a pipeline. Your data is lab-specific; the
        figures aren&apos;t. Skip if you already know which skills to run.
      </p>

      <div className="grid gap-4 sm:grid-cols-2">
        {questions.map((q) => (
          <div key={q.id} className={q.type === "textarea" ? "sm:col-span-2 space-y-1.5" : "space-y-1.5"}>
            <Label htmlFor={q.id}>{q.label}</Label>
            {q.type === "select" ? (
              <Select value={answers[q.id] ?? ""} onValueChange={(v) => set(q.id, v)}>
                <SelectTrigger id={q.id} aria-label={q.label}>
                  <SelectValue placeholder="Select…" />
                </SelectTrigger>
                <SelectContent>
                  {(q.options ?? []).map((o) => (
                    <SelectItem key={o} value={o}>
                      {o}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            ) : q.type === "textarea" ? (
              <textarea
                id={q.id}
                value={answers[q.id] ?? ""}
                onChange={(e) => set(q.id, e.target.value)}
                placeholder={q.placeholder}
                rows={2}
                className="w-full resize-y rounded-md border border-input bg-background/60 px-3 py-2 text-sm text-foreground outline-none placeholder:text-muted-foreground/60 focus-visible:border-ring/60 focus-visible:ring-2 focus-visible:ring-ring/30"
              />
            ) : (
              <Input
                id={q.id}
                value={answers[q.id] ?? ""}
                onChange={(e) => set(q.id, e.target.value)}
                placeholder={q.placeholder}
              />
            )}
            {q.helper && <p className="text-[11px] text-muted-foreground">{q.helper}</p>}
          </div>
        ))}
      </div>

      <div className="flex items-center gap-2 pt-1">
        <Button type="submit" size="sm">
          <Sparkles /> Propose a pipeline
        </Button>
        <Button type="button" variant="ghost" size="sm" onClick={onSkip}>
          Skip — I&apos;ll pick skills
        </Button>
      </div>
    </form>
  );
}
